### PR TITLE
Initial version of SentStructure.js visualizer

### PR DESCRIPTION
**Pull request by adrianeboyd**
Implements a visualization for token-token alignments between parallel
texts using SentStructure.js
(https://gitlab.cl.uzh.ch/sparcling/SentStructure.js)

The visualization is called `sentstructurejs` and has the mapping option
`alignment_label` for optional alignment labels.

SentStructure.js modifications:

* support color highlighting of tokens
* add labels to alignment paths
* disable zoom and drag

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Test using:

[parallel.sample.3langs.annis.zip](https://github.com/korpling/ANNIS/files/2449256/parallel.sample.3langs.annis.zip) with query:

    tok & tok & tok & #1 ->align_f-g[type="good"] #2 & #2 ->align_g-e[type="good"] #3

[SMULTRON_Banana_relAnnis.modified.zip](https://github.com/korpling/ANNIS/files/2449257/SMULTRON_Banana_relAnnis.modified.zip) with query:

    tok & tok & #1 ->align_d-e[type="fuzzy"] #2

[English.zip](https://github.com/korpling/ANNIS/files/2449255/English.zip) with query:

    tok & tok & #1 ->align #2

**Comment by thomaskrause** [comment]
Thank you very much for the pull request! Having a visualization of the parallel corpus alignment is really useful. I think it is perfectly fine to be included code-wise, but we need a clarification with the license of the SentStructure.js library which use use (https://gitlab.cl.uzh.ch/sparcling/SentStructure.js). Currently, this project does not have any license and thus can't be included in other software. I'm sure this was not the intention of the original author, do you know if he can publish the SentStructure.js under a license we can use (e.g. Apache License Version 2 https://apache.org/licenses/LICENSE-2.0)?

**Comment by adrianeboyd** [comment]
I got in touch with the author and he has added an Apache 2.0 License: https://github.com/Christof93/SentStructure/LICENSE .

**Comment by thomaskrause** [comment]
Thank you very much! I will reference the license in a later commit in our documentation, but I already integrate the workings state into the develop branch.

**Pull request merged**
